name: Python Lint

on: [push, pull_request]

jobs:
  build:
    env:
      working-dir: ./api

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]

    steps:
    - uses: actions/checkout@v2
      with:
          token: ${{ secrets.DEV_47_TOKEN }}

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install black
      working-directory: ${{env.working-dir}}

    - name: Analysing the code with black
      run: |
        black . -v
      working-directory: ${{env.working-dir}}

    - name: Setting Identify for Git
      run: |
        git config user.email "dev-47.pilot@dev-47.com"
        git config user.name "Dev 47 Pilot"

    - name: Fetching changes from remote url on HTTPS
      run: |
        git remote add origin https://github.com/Dev-47/quiz-app.git
        git pull origin main

    - name: Check for changes
      run: git status

    - name: Stage changed files
      run: |
        git add .

    - name: Commit changed files
      run: |
        git commit -m "GH-ACTIONS / updates new linted files"

    - name: Push code to main
      run: |
        git push origin HEAD:main
      working-directory: ${{env.working-dir}}
